### ISSUE TITLE
请问：大学物理实验的实验表格模板的声速的测量的计算波长的不确定度的公式是否有误？

### ISSUE THREAD

**Issue by FuxuanNet** [HEUOpenResource/heu-icicles#18]
表格上所给的公式是 ` =SQRT(STDEV.S(B11:K11)^2+SQRT(2*E6^2)) ` .

但是我发现书中给的公式中，B 类不确定度是要加平方的。

我认为公式可能如下：
`=SQRT(STDEV.S(B11:K11)^2+SQRT(2*E6^2)^2)`

其中，A 类不确定度为：
`=STDEV.S(B11:K11)`

B 类不确定度为：
`=SQRT(2*E6^2)`

总不确定度为根号下的 A 与 B 的平方和。

原表格中可能少了 B 的平方。

**Comment by RigelNana** [comment]
qwq是的，漏了一个平方，之后会与其他资料一齐pr修正
